import { createInitialState, hashGameState, step } from "@mercicat/simulation";
import { SeededRandom, type GameState, type InputCommand, type PlayerId } from "@mercicat/shared";
import { PlayerInputBuffer } from "./inputBuffer";
export interface RoomPlayer { playerId: PlayerId; socketId: string | null; connected: boolean; ready: boolean; disconnectedAt?: number; }
export class GameRoom {
  readonly players: RoomPlayer[] = []; readonly inputBuffers = new Map<PlayerId, PlayerInputBuffer>(); readonly rng: SeededRandom; state: GameState; private sequence = 0;
  constructor(readonly id: string, seed: number | string = 1) { this.rng = new SeededRandom(seed); this.state = createInitialState(seed, []); }
  join(playerId: PlayerId, socketId: string): boolean { const old = this.players.find((p) => p.playerId === playerId); if (old) { old.socketId = socketId; old.connected = true; delete old.disconnectedAt; return true; } if (this.players.length >= 4) return false; const entityId = this.state.nextEntityId++; this.state.players[playerId] = entityId; this.state.entities[entityId] = { id: entityId, kind: "player", lifecycle: "active", playerId, position: { x: 0, y: 0 }, velocity: { x: 0, y: 0 }, radius: 12, health: 100, maxHealth: 100, spawnTick: this.state.tick, despawnTick: null, fireCooldownTicks: 0 }; this.players.push({ playerId, socketId, connected: true, ready: false }); this.inputBuffers.set(playerId, new PlayerInputBuffer(playerId)); return true; }
  leave(playerId: PlayerId, now = Date.now()): void { const p = this.players.find((v) => v.playerId === playerId); if (p) { p.connected = false; p.socketId = null; p.ready = false; p.disconnectedAt = now; } }
  prune(now = Date.now()): PlayerId[] { const removed: PlayerId[] = []; for (let i = this.players.length - 1; i >= 0; i--) { const p = this.players[i]; if (!p.connected && p.disconnectedAt !== undefined && now - p.disconnectedAt >= 30000) { removed.push(p.playerId); this.players.splice(i, 1); this.inputBuffers.delete(p.playerId); delete this.state.players[p.playerId]; } } return removed; }
  ready(playerId: PlayerId, value = true): boolean { const p = this.players.find((v) => v.playerId === playerId); if (!p || !p.connected) return false; p.ready = value; return true; }
  receiveInput(playerId: PlayerId, input: unknown): boolean { if (!this.players.some((p) => p.playerId === playerId && p.connected)) return false; const value = input as { tick?: number; command?: InputCommand; sequence?: number }; if (value.tick === undefined || value.tick > this.state.tick || value.command?.playerId !== playerId) return false; return this.inputBuffers.get(playerId)?.enqueue({ sequence: value.sequence ?? this.sequence++, tick: value.tick, command: value.command }, this.state.tick) ?? false; }
  tick() { const commands: InputCommand[] = []; for (const [id, buffer] of this.inputBuffers) commands.push(...buffer.drain(this.state.tick).map((c) => ({ ...c, playerId: id }))); const result = step(this.state, commands, { rng: this.rng }); this.state = result.state; return { snapshot: this.snapshot(), gameOver: this.state.phase !== "playing" }; }
  snapshot() { return { tick: this.state.tick, state: structuredClone(this.state), rngState: this.rng.serialize(), stateHash: hashGameState(this.state), acknowledgedThrough: Math.max(-1, ...[...this.inputBuffers.values()].map((b) => b.lastAcceptedSequence)) }; }
  get connectedCount(): number { return this.players.filter((p) => p.connected).length; }
}